// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/witchcraft1/Architecture-course-2/server/dormitories"
)

// Injectors from modules.go:

func ComposeApiServer(port HttpPortNumber) (*DormitoryApiServer, error) {
	db, err := NewDbConnection()
	if err != nil {
		return nil, err
	}
	store := dormitories.NewStore(db)
	httpHandlerFunc := dormitories.HttpHandler(store)
	dormitoryApiServer := &DormitoryApiServer{
		Port:            port,
		DormitoriesHandler: httpHandlerFunc,
	}
	return dormitoryApiServer, nil
}
